version: 1.0.{build}

environment:
  PATH: 'C:\Python27;C:\Python27\Scripts;%PATH%'
  TARGET: 'nightly-x86_64-pc-windows-msvc'

install:
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\vcvars64.bat"
  - ps: Start-FileDownload "https://dl.dropboxusercontent.com/u/25971865/msvc-deps/moztools-0.0.1-4.zip"
  - 7z x moztools-0.0.1-4.zip
  - set "MOZTOOLS_PATH=%APPVEYOR_BUILD_FOLDER%\moztools-0.0.1-4\bin"
  - set RUST_BACKTRACE=1
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe" -FileName "rust-install.exe"
  - ps: .\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"

# Uncomment these lines to expose RDP access information to the build machine in the build log.
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
  - cargo build -v

test: off
