version: 1.0.{build}

environment:
  PATH: 'C:\Python27;C:\Python27\Scripts;%PATH%'
  TARGET: 'nightly-x86_64-pc-windows-msvc'

install:
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\vcvars64.bat"
  - ps: Start-FileDownload "https://dl.dropboxusercontent.com/u/25971865/msvc-deps/moztools-0.0.1-4.zip"
  - 7z x moztools-0.0.1-4.zip
  - set "MOZTOOLS_PATH=%APPVEYOR_BUILD_FOLDER%\moztools-0.0.1-4\bin"
  - set "PATH=%APPVEYOR_BUILD_FOLDER%\moztools-0.0.1-4\bin;%PATH%"
  - set RUST_BACKTRACE=1
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe" -FileName "rust-install.exe"
  - ps: .\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  # Setup CL_CACHE
  - ps: Start-FileDownload "https://dl.dropboxusercontent.com/u/25971865/msvc-deps/clcache.zip"
  - 7z x clcache.zip
  - cmd: IF EXIST %APPVEYOR_BUILD_FOLDER%\clcache-3.2.0 ECHO clcache-3.2.0 exist.
  - set "MSVC_BIN=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\"
  - cmd: MOVE "%MSVC_BIN%cl.exe" "%MSVC_BIN%cl_original.exe"
  - cmd: MOVE "%MSVC_BIN%cl.exe.config" "%MSVC_BIN%cl_original.exe.config"
  - cmd: MOVE "%APPVEYOR_BUILD_FOLDER%\clcache.exe" "%MSVC_BIN%cl.exe"
  - set "CLCACHE_CL=%MSVC_BIN%cl_original.exe"
  - cl -s

# Uncomment these lines to expose RDP access information to the build machine in the build log.
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
  - cargo build -v
  - cl -s

test: off
